name: Evaluate System Prompt
description: Evaluate a system prompt via the Circuit Breaker Labs API.
inputs:
  fail-action-threshold:
    description: Failure rate above this threshold will fail the workflow.
    required: true
  fail-case-threshold:
    description: Threshold score where an individual case is considered failed.
    required: true
  variations:
    description: Number of test variations to run.
    required: true
  maximum-iteration-layers:
    description: Maximum iteration layers for the evaluation.
    required: true
  system-prompt:
    description: System prompt text to evaluate.
    required: true
  openrouter-model-name:
    description: OpenRouter model name to evaluate against.
    required: true
  circuit-breaker-labs-api-key:
    description: Circuit Breaker Labs API key (store as a secret).
    required: true
runs:
  using: composite
  steps:
    - name: Install uv
      shell: bash
      run: |
        set -eo pipefail
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
    - name: Evaluate system prompt
      shell: bash
      working-directory: ${{ github.action_path }}/..
      env:
        FAIL_ACTION_THRESHOLD: ${{ inputs.fail-action-threshold }}
        FAIL_CASE_THRESHOLD: ${{ inputs.fail-case-threshold }}
        VARIATIONS: ${{ inputs.variations }}
        MAXIMUM_ITERATION_LAYERS: ${{ inputs.maximum-iteration-layers }}
        SYSTEM_PROMPT: ${{ inputs.system-prompt }}
        OPENROUTER_MODEL_NAME: ${{ inputs.openrouter-model-name }}
        CBL_API_KEY: ${{ inputs.circuit-breaker-labs-api-key }}
      run: |
        set -eo pipefail
        uv run evaluate-system-prompt \
          --fail-action-threshold "$FAIL_ACTION_THRESHOLD" \
          --fail-case-threshold "$FAIL_CASE_THRESHOLD" \
          --variations "$VARIATIONS" \
          --maximum-iteration-layers "$MAXIMUM_ITERATION_LAYERS" \
          --system-prompt "$SYSTEM_PROMPT" \
          --openrouter-model-name "$OPENROUTER_MODEL_NAME" \
          --circuit-breaker-labs-api-key "$CBL_API_KEY"
